name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main", "master" ] # 监听主分支的推送
  workflow_dispatch:           # 支持手动触发构建

# 必须设置权限，允许 Action 写入 Pages 并生成身份 Token
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 💡 极其重要：设为 0 拉取完整历史，解决 pnpm 过滤器找不到项目的问题
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Project
        run: pnpm build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 无名杀脚本打包后，最终合并出来的静态文件存放在根目录的 dist 文件夹
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
